pref('extensions.FacebookApp@blueimp.net.description', 'chrome://FacebookApp/locale/FacebookApp.properties');
pref('extensions.FacebookApp@blueimp.net.shortcut', 'chrome://FacebookApp/locale/FacebookApp.properties');
pref('extensions.FacebookApp@blueimp.net.hideStatusbarIcon',true);
pref('extensions.FacebookApp@blueimp.net.hideToolsMenu',false);
pref('extensions.FacebookApp@blueimp.net.hideContextMenuItem',true);
pref('extensions.FacebookApp@blueimp.net.hideToolbarButton',false);
pref('extensions.FacebookApp@blueimp.net.hideToolbarButtonMenu',true);
pref('extensions.FacebookApp@blueimp.net.searchLoginsOnload',false);
pref('extensions.FacebookApp@blueimp.net.skipDuplicateActionForms',true);
pref('extensions.FacebookApp@blueimp.net.highlightColor','#FF9900');
pref('extensions.FacebookApp@blueimp.net.highlightOutlineStyle','solid');
pref('extensions.FacebookApp@blueimp.net.highlightOutlineWidth',1);
pref('extensions.FacebookApp@blueimp.net.highlightOutlineRadius',5);
pref('extensions.FacebookApp@blueimp.net.highlightStyle','');
pref('extensions.FacebookApp@blueimp.net.autoSubmitForm',true);
pref('extensions.FacebookApp@blueimp.net.javascriptProtection',false);
pref('extensions.FacebookApp@blueimp.net.playLoginFoundSound',false);
pref('extensions.FacebookApp@blueimp.net.playLoginSound',false);
pref('extensions.FacebookApp@blueimp.net.exceptionList','');
pref('extensions.FacebookApp@blueimp.net.autofillFormsOnLogin',false);
pref('extensions.FacebookApp@blueimp.net.FacebookAppBookmarks',false);
pref('extensions.FacebookApp@blueimp.net.FacebookAppBookmarkHash','#FacebookAppBookmark');
pref('extensions.FacebookApp@blueimp.net.autoLogin',false);
pref('extensions.FacebookApp@blueimp.net.autoLoginExceptions','');
pref('extensions.FacebookApp@blueimp.net.defaultNotificationTimeout',3000);
pref('extensions.FacebookApp@blueimp.net.defaultNotificationImage','chrome://FacebookApp/skin/login-small.png');
pref('extensions.FacebookApp@blueimp.net.helpURL', 'http://FacebookApp.mozdev.org/drupal/wiki/[TOPIC]');